version: "3"
services:
    book-php:
        image: "pauulog/php-docker-dev:latest"
        container_name: "book-php"
        links:
          - "book-mariadb:mariadb.host"
        volumes:
            - "./:/h3-book:rw"
        working_dir: /h3-book
        restart: always
    book-nginx:
        image: "nginx:1-alpine"
        container_name: "book-nginx"
        links:
          - "book-php:book-php.host"
        ports:
          - 8080:80
        volumes:
            - "./:/h3-book:rw"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:r"
        working_dir: /h3-book
        restart: always
    book-mariadb:
        image: "mariadb:10.6"
        container_name: "book-mariadb"
        volumes:
            - "._mysql_data_dir/:/var/lib/mysql:rw"
        ports:
          - 3307:3306
        environment:
          - MARIADB_USER
          - MARIADB_PASSWORD
          - MARIADB_DATABASE
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
        restart: always